sync:
  - file-path: ../web/apps/expenses/dist
    directory-name: portals/expenses
  - file-path: ../web/apps/tasks/dist
    directory-name: portals/tasks
  - file-path: ../web/apps/time-tracking/dist
    directory-name: portals/time-tracking
